//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogue.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiErrorMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiErrorMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catalogue.API.Resources.ApiErrorMessagesResource", typeof(ApiErrorMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the &apos;Id&apos; property in the request object does not match the type of the &apos;id&apos; value from the route. Expected type: {0}, Actual type: {1}. Ensure that the &apos;Id&apos; property and route value types are consistent..
        /// </summary>
        public static string ID_PROPERTY_NOT_EQUAL_ERROR {
            get {
                return ResourceManager.GetString("ID_PROPERTY_NOT_EQUAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; property is null or not found in the request object. Ensure that the request object contains a public property named &apos;Id&apos; and that it is properly initialized..
        /// </summary>
        public static string ID_PROPERTY_NULL_ERROR {
            get {
                return ResourceManager.GetString("ID_PROPERTY_NULL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the &apos;Name&apos; property in the request object does not match the type of the &apos;Name&apos; value from the route. Expected type: {0}, Actual type: {1}. Ensure that the &apos;Name&apos; property and route value types are consistent..
        /// </summary>
        public static string NAME_PROPERTY_NOT_EQUAL_ERROR {
            get {
                return ResourceManager.GetString("NAME_PROPERTY_NOT_EQUAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Invalid.
        /// </summary>
        public static string QUERY_INVALID {
            get {
                return ResourceManager.GetString("QUERY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request object is missing. Ensure that the request object is the first parameter in the endpoint configuration and verify that it is being correctly passed..
        /// </summary>
        public static string REQUEST_NULL_FILTER_ERROR {
            get {
                return ResourceManager.GetString("REQUEST_NULL_FILTER_ERROR", resourceCulture);
            }
        }
    }
}
